XRPchart.py

[リップル のチャートの作成]()
- 前回と同じ
- 
- 
- 
- 
- 
- 
- 
- 
-

#5 pushのやり直し

---

LlneAlert.py

[LINEへの価格通知]
- 通知機能
- 
- 
- 
- 
- LINE
- 
- 
- 
-

LINEへの価格通知 #13

---

XRPchart.py

[XRPchart.pyをCCXTを用いてチャートを表示する]()
- 
- 
- 
- 
- 
- 
- 
- 
- 
-

#17 #5のコードをCCXTを用いてチャートを表示するように変更した

---

BitbankExchange.py

[#8 bitbankから取得した価格をBTCに変換する]
- 取得した価格を変換する式を追加した
- とりあえず大まかにできたくらいなので、確認・テスト・修正が必要
- なし
- 
- 実行できなかった
-
-

Add bitbank exchange

---

LineAlert.py

[別ファイルからアクセストークン取得]
- アクセストークンを別ファイルにから読み込むように変更
- pylintの点数を上げる
- 
- 
-　-0.56
-
-

別ファイルからアクセストークン取得　＃29

---

app/xrpchart.py

[#27 のファイルをpushし直しました]
- 
- 
- 
- 
-
-
-

#27のxrpchart.pyをpushし直しました

---

app/module/__init__.py

[#34 ]
- __init__.pyファイルを作成しモジュールを一つに纏めた
- 
- 
- 
-パッケージのため点数なし
-
-pythonのバージョンによっては動かないので最新版で実行してください

複数のモジュールをパッケージに纏めた

---

app/module/exchanges_binance.py
app/module/exchanges_bitbank.py

コメントの空白行を修正

---

app/module/xrp_to_btc.py

[モジュール名の変更]
- BitbankExchange.pyをxrp_to_btc.pyに変更した
- 
- 
- 
-
-
-

modify-BitbankExchangeの名前をxrp_to_btcに変更

---

app/module/__init__.py
app/xrpchart.py

[]
- ./module/exchanges_bitbank.py
./module/exchanges_binance.py
- 
- 
- 
-  (8.91/10.0)
-
-実行する際に時間がかかりtimeoutが発生するために10秒のtimesleepを2回発生させて約20秒ごとに1回の感覚で値をとってくるようにしている。

xrpchartを二つの取引所からチャートを表示するようにした。

---

app/line_alert.py

[なし]
- 
- pulintの点数を満点にした。
- 
- 
-10
- igunoaファイルがない場合はエラーが増えます。
-

pylintの点数あげ

---

app/module/Currency_exchange.py
app/module/btc_to_jpy.py
app/module/exchanges.py
app/module/xrp_to_btc.py
app/xrpchart.py
test/test_exchanges.py

[exchanges.pyのテスト作成]
- unittest仕様
- 
- 
- coverage が実行できない
-test_exchanges.py 9.29/10
-W: 18, 8: Using deprecated method assertEquals() (deprecated-method)
-

Test creation

---

app/line_alert.py

[LINEアラート改良]
- DBからトークンキーを取得
-ステータスコード取得
- 
- re　理由：正規表現を使用したかったため
- 
-　7.41
-
-

LINEアラート改良

---

.travis.yml
test/test_exchanges.py

[自動テスト環境の構築]
- テストを実行時に記名されているバージョンで実行しているかどうかを確認する一文の追加
- 特になし
- 
- 
-
-
-

pythonのバージョン確認の一文の追加

---

app/module/exchangess/binance.py
app/module/exchangess/bitbank.py
test/test_binance.py
test/test_bitbank.py

[特になし]
- 取引所モジュールのメソッド参照回数が9回と多かったので5回までに減らした
- 特になし（動きに変更はないため）
- 
- なし
-平均で８点
-import文の優先順位でエラーを出すが気にしなくてもいい。
-

Add transfer

---

app/module/exchangess/bitbank.py
app/module/money_exchange/btc_to_jpy.py
app/module/money_exchange/xrp_to_btc.py
test/test_bitbank.py

[]
- 
- 
- 
- 
-test_bitbank.py(7.78/10)
bitbank.py(10.00/10)
- ************* Module test.test_bitbank
C:  5, 0: Import "import unittest" should be placed at the top of the module (wrong-import-position)
C:  6, 0: Import "from app.module.exchangess import bitbank" should be placed at the top of the module (wrong-import-position)
C: 18, 4: Missing method docstring (missing-docstring)
C: 22, 4: Missing method docstring (missing-docstring)
-

bitbank.pyの変更及びtest_bitbank.pyの変更

---

.travis.yml

[自動テスト環境の構築 #84]
- Travis CI
- カバレッジを取得してレポートを送信させるようにしたい。
- 
- 
-
-
-

chore:travis.ciの設定にslackに通知するように設定を追加、メールに通知しないように設定追加

---

app/module/exchangess/binance.py

[なし]
- なし
- binance .pyの評価が低かったためbitbankと似た作りにした。
- 
- 
-9点
-impoer文のエラーだが気にしないで。
-

finance .py no

---

app/main_menu.py
main_menu.py

[取引所価格のリアルタイムを取得]
- メイン画面でのチャートの表示
- 
- 
- 
-
-  +3.97
-

取引所価格のリアルタイムを取得

---

app/main_menu.py

[メイン画面上の機能追加]
- スクロールバー
- 通貨ごとの価格取得
- 通貨価格のリアルタイム処理
- チャートをmainウィンドウ内に表示
- 
- 
-　4.43/10
-
-

メイン画面上の機能追加

---

app/main_menu.py

[画面デザインの変更など]
- チャートを画像にし、画面に組み込む
-取得取引所の整理
- 画像の切り替え、作成
- なし
- 
-　6.09/10
-
-

画面デザインの変更など

---

app/graphcreation.py

[グラフに凡例を表示させる]
- 
- 
- 
- 
- 5.96/10 
-No config file found, using default configuration
************* Module app.graphcreation
C: 34, 0: Line too long (113/100) (line-too-long)
C: 83, 0: Final newline missing (missing-final-newline)
C:  1, 0: Missing module docstring (missing-docstring)
C:  9, 0: Argument name "Df" doesn't conform to snake_case naming style (invalid-name)
C:  9, 0: Argument name "Number" doesn't conform to snake_case naming style (invalid-name)
C:  9, 0: Missing function docstring (missing-docstring)
C: 13, 0: Argument name "Df" doesn't conform to snake_case naming style (invalid-name)
C: 13, 0: Argument name "Number" doesn't conform to snake_case naming style (invalid-name)
C: 13, 0: Missing function docstring (missing-docstring)
C: 23, 0: Missing class docstring …

グラフに凡例を表示させる

---

app/main_menu.py

[graphcreationから画像生成しそれを表示]
- 
- 
- 
- 
-
-
-

graphcreationから画像生成し表示

---

app/module/exchangess/binance.py
app/module/exchangess/bitbank.py

[取引所から指定したIDと通貨ペアを持つ注文をキャンセルする処理を追加]
- 
- 
- 
- 
-
-
-

Add cancel order
